---
apiVersion: v1
kind: Pod
metadata:
  name: maas
  labels:
    app: maas
spec:
  #hostNetwork: true
  containers:
    - name: maas
      image: ghcr.io/dhain/maas:3.1
      imagePullPolicy: Always
