---
apiVersion: v1
kind: Service
metadata:
  name: maas
  labels:
    app: maas
spec:
  clusterIP: 10.21.0.32
  selector:
    app: maas
  ports:
    - port: 5240
      name: http
    - port: 3128
      name: proxy
    - port: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      name: dns-tcp

---
apiVersion: v1
kind: Pod
metadata:
  name: maas
  labels:
    app: maas
spec:
  #hostNetwork: true
  containers:
    - name: maas
      image: ghcr.io/dhain/maas:3.1
      imagePullPolicy: Always
      ports:
        - containerPort: 5240
          name: http
        - containerPort: 3128
          name: proxy
        - containerPort: 53
          protocol: UDP
          name: dns-udp
        - containerPort: 53
          name: dns-tcp
      readinessProbe:
        httpGet:
          port: 5240
          path: /MAAS/r/
        initialDelaySeconds: 5
        periodSeconds: 60
    - name: postgres
      image: postgres:12
      args: ["-c", "listen_addresses=127.0.0.1"]
      env:
        - name: POSTGRES_USER
          value: maas
        - name: POSTGRES_PASSWORD
          value: changeme
        - name: POSTGRES_DB
          value: maasdb
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - psql -h 127.0.0.1 "$POSTGRES_DB" "$POSTGRES_USER" -c 'select 1;'
        initialDelaySeconds: 5
        periodSeconds: 10
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: pgdata
      emptyDir: {}
