---
apiVersion: v1
kind: Pod
metadata:
  name: maas
  labels:
    app: maas
    component: regiond-rackd
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: maas
      image: ghcr.io/dhain/maas:3.1
      imagePullPolicy: Always
      env:
        - name: PG_HOST
          value: postgres
      ports:
        - containerPort: 5240
          name: http
        - containerPort: 3128
          name: proxy
        - containerPort: 53
          protocol: UDP
          name: dns-udp
        - containerPort: 53
          name: dns-tcp
      readinessProbe:
        httpGet:
          port: 5240
          path: /MAAS/r/
        initialDelaySeconds: 5
        periodSeconds: 60
      volumeMounts:
        - name: proxy-cache
          mountPath: /var/spool/maas-proxy
  volumes:
    - name: proxy-cache
      hostPath:
        path: /var/spool/maas-proxy
        type: DirectoryOrCreate
