---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  podSelector:
    matchLabels:
      app: postgres
  ingress:
    - from:
      - podSelector:
          matchLabels:
            component: regiond
      - podSelector:
          matchLabels:
            component: rackd
      ports:
        - protocol: TCP
          port: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_USER
              value: maas
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_DB
              value: maasdb
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
