---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rackd
  labels:
    app: rackd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rackd
  template:
    metadata:
      labels:
        app: rackd
        component: rackd
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: rackd
          image: ghcr.io/dhain/maas:3.1
          imagePullPolicy: Always
          args: ["rack"]
          env:
            - name: MAAS_URL
              value: http://maas:5240/MAAS
            - name: MAAS_SECRET
              value: 00e1688bd6d8d9c909e8467371113e7c
